name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout source code
        uses: actions/checkout@v4
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build Docker image
        run: |
         pwd 
          echo "Building Docker image with tag: $TAG"
          docker build -t maiekel259041/flask -f ./app/Dockerfile .
      - name: push Docker image 
        run: |
         docker push maiekel259041/flask
         
        
